"""added one to many relationship between School and Course models

Revision ID: 2a1225a56376
Revises: 562796c021a8
Create Date: 2026-01-15 12:12:40.848544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1225a56376'
down_revision: Union[str, Sequence[str], None] = '562796c021a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'school_id')
    # ### end Alembic commands ###
