"""reduced the max length of AlumniProfile's prefix attribute to 15

Revision ID: 30ab057ba539
Revises: 689a73e7afa4
Create Date: 2026-01-13 20:00:12.955531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30ab057ba539'
down_revision: Union[str, Sequence[str], None] = '689a73e7afa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_profiles', 'prefix',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_profiles', 'prefix',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
