"""made the title and normalized_title field in Occupation model unique

Revision ID: 3398bfaadd74
Revises: e838cf7628d1
Create Date: 2026-01-14 17:43:09.167920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3398bfaadd74'
down_revision: Union[str, Sequence[str], None] = 'e838cf7628d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'occupations', ['normalized_title'])
    op.create_unique_constraint(None, 'occupations', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'occupations', type_='unique')
    op.drop_constraint(None, 'occupations', type_='unique')
    # ### end Alembic commands ###
