"""added JobPostInterest junction table to enable alumni to show their interests on job posts

Revision ID: 4632da75b0e1
Revises: 6ebe4586e5f0
Create Date: 2026-01-30 22:38:43.603348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4632da75b0e1'
down_revision: Union[str, Sequence[str], None] = '6ebe4586e5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_post_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=True),
    sa.Column('alumni_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alumni_profile_id'], ['alumni_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_post_interests_id'), 'job_post_interests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_post_interests_id'), table_name='job_post_interests')
    op.drop_table('job_post_interests')
    # ### end Alembic commands ###
