"""updated AlumniProfile's prefix attribute to name_extension

Revision ID: 562796c021a8
Revises: 3398bfaadd74
Create Date: 2026-01-14 18:47:12.052823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '562796c021a8'
down_revision: Union[str, Sequence[str], None] = '3398bfaadd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_profiles', sa.Column('name_extension', sa.String(length=15), nullable=True))
    op.drop_column('alumni_profiles', 'prefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_profiles', sa.Column('prefix', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('alumni_profiles', 'name_extension')
    # ### end Alembic commands ###
