"""added is_reviwed attribute to JobPostInterest model to determine which alumni CVs are already reviwed by the company

Revision ID: 665657995312
Revises: 4632da75b0e1
Create Date: 2026-01-31 00:01:43.010294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665657995312'
down_revision: Union[str, Sequence[str], None] = '4632da75b0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post_interests', sa.Column('is_reviewed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post_interests', 'is_reviewed')
    # ### end Alembic commands ###
