"""made AlumniProfile's profile_picture_filename optional

Revision ID: 689a73e7afa4
Revises: f53fe7be3910
Create Date: 2026-01-13 19:53:30.740569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '689a73e7afa4'
down_revision: Union[str, Sequence[str], None] = 'f53fe7be3910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_profiles', 'profile_picture_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_profiles', 'profile_picture_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
