"""added normalized_name for School and Course models

Revision ID: 6df7b1ef0f30
Revises: 2a1225a56376
Create Date: 2026-01-15 18:25:47.766667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df7b1ef0f30'
down_revision: Union[str, Sequence[str], None] = '2a1225a56376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('normalized_name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'courses', ['normalized_name'])
    op.create_unique_constraint(None, 'courses', ['name'])
    op.add_column('schools', sa.Column('normalized_name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'schools', ['normalized_name'])
    op.create_unique_constraint(None, 'schools', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_column('schools', 'normalized_name')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'normalized_name')
    # ### end Alembic commands ###
