"""renamed JobPost model's is_open attribute to is_published

Revision ID: 6ebe4586e5f0
Revises: 7262dab7aca7
Create Date: 2026-01-29 20:40:18.047006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ebe4586e5f0'
down_revision: Union[str, Sequence[str], None] = '7262dab7aca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.drop_column('job_posts', 'is_open')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('is_open', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('job_posts', 'is_published')
    # ### end Alembic commands ###
