"""renamed JobPost model's is_posted_already attribute to is_open

Revision ID: 7262dab7aca7
Revises: 1333a4d19127
Create Date: 2026-01-29 20:31:41.023596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7262dab7aca7'
down_revision: Union[str, Sequence[str], None] = '1333a4d19127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('is_open', sa.Boolean(), nullable=False))
    op.drop_column('job_posts', 'is_posted_already')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('is_posted_already', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('job_posts', 'is_open')
    # ### end Alembic commands ###
