"""updated CompanyProfile's location attribute into address

Revision ID: df41fb6d25cb
Revises: 0bfc7ead1bf3
Create Date: 2026-01-12 19:08:24.884627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df41fb6d25cb'
down_revision: Union[str, Sequence[str], None] = '0bfc7ead1bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('address', sa.String(length=1025), nullable=False))
    op.drop_column('company_profiles', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('location', mysql.VARCHAR(length=1025), nullable=False))
    op.drop_column('company_profiles', 'address')
    # ### end Alembic commands ###
