"""added normalized_title field in Occupation model

Revision ID: e838cf7628d1
Revises: 30ab057ba539
Create Date: 2026-01-14 17:39:00.900924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e838cf7628d1'
down_revision: Union[str, Sequence[str], None] = '30ab057ba539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupations', sa.Column('normalized_title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupations', 'normalized_title')
    # ### end Alembic commands ###
